[package]
name = "actix_back"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-rt = "2.10.0"
actix-web = { version = "4.11.0", features = ["openssl"] }
env_logger = "0.11.8"
openssl = "0.10.73"

